# Generated by Django 4.2.7 on 2026-02-15 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_predictions', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Analytics Stats',
                'verbose_name_plural': 'Analytics Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SentimentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Original text for analysis')),
                ('cleaned_text', models.TextField(help_text='Preprocessed text')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Predicted sentiment', max_length=10)),
                ('confidence', models.FloatField(default=0.0, help_text='Prediction confidence score')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sentiment Prediction',
                'verbose_name_plural': 'Sentiment Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
